# Generated by Django 4.2.5 on 2023-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPatrioticMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('creationyear', models.CharField(max_length=200)),
            ],
        ),
    ]
